### PR TITLE
Fix fetchn on queries with zero results

### LINKED ISSUE #352: Documentation has syntax error for next auto_increment value
### Description
The documentation has a syntax mistake. In `docs-parts/definition/07-Primary-Key_lang1.rst`, it describe it as:
```matlab
key.scah_idx = fetch1(Scan & key, 'next=max(scan_idx)+1')
```

### Expected Behavior
It should be:
```matlab
key.scan_idx = fetch1(Scan & key, 'max(scan_idx)+1 -> next')
```

### Screenshots
image

### Additional Research and Context
Raised in this DataJoint Slack [thread](https://datajoint.slack.com/archives/C4284EUG4/p1615555321015000?thread_ts=1615317582.001500&cid=C4284EUG4).

### LINKED ISSUE #353: bug with fetchn in  DJ 3.4.1 MATLAB
### Description

I switched to DJ 3.4.1 and the behavior of "fetchn" had changed.  In older versions, if the query was empty "fetchn" used to return just an empty result. But in the new version it throws an error. To solve this I now need to wrap every fetchn with an if statement to check that the query is not empty, which is very cumbersome.

### Reproducibility
Include:
- OS (WIN | MACOS | Linux) WINDOWS
- MATLAB Version 2019a
- MySQL Version
- MySQL Deployment Strategy (local-native | local-docker | remote)
- DataJoint Version 3.4.1
- Minimum number of steps to reliably reproduce the issue
- Complete error stack as a result of evaluating the above steps

### Expected Behavior

I expect to get an empty result of the fetchn. 

Instead I get:

tr_ignore = fetchn(EXP.BehaviorTrial & key & 'outcome="ignore"','trial');
Index exceeds the number of array elements (0).

Error in dj.internal.GeneralRelvar/fetchn (line 292)
                if isnumeric(s(1).(name{1}{1})) && length(s(1).(name{1}{1})) == 1

### PR DESCRIPTION
**Pull request by guzman-raphael**
Depends on datajoint/mysql-docker#29
Fix #353
Fix #352

### CODE REVIEW

**Review by dimitri-yatsenko — APPROVED** [review]
Looks great!

**Review by dimitri-yatsenko — APPROVED** [review]

File: +dj/+internal/GeneralRelvar.m [hunk 1]
```diff
@@ -289,7 +289,8 @@ function clip(self)
             for iArg=1:length(specs)
                 % if renamed, use the renamed attribute
                 name = regexp(specs{iArg}, '(\w+)\s*$', 'tokens');
-                if isnumeric(s(1).(name{1}{1})) && length(s(1).(name{1}{1})) == 1
+                sel = cellfun(@(x) strcmp(x, name{1}{1}), {self.header.attributes.name});
+                if self.tableHeader.attributes(sel).isNumeric
```
Comment (ixcat) [inline +dj/+internal/GeneralRelvar.m:293]: this may have introduced a regression - received a report elsewhere:

```
To fix the bug I changed:
In dj.internal.GeneralRelvar  (line 293) I changed
if self.tableHeader.attributes(sel).isNumeric
to
if self.header.attributes(sel).isNumeric
```

Comment (ixcat) [reply +dj/+internal/GeneralRelvar.m:293]: looks like this has been filed as an issue in: https://github.com/datajoint/datajoint-matlab/issues/364; disregard discussion here.
