### PR TITLE
Fix SQL argument growth condition

### LINKED ISSUE #217: External Blob: Insert fails due to `foreign key constraint` in `~external_%` table
Princeton reported an error that `Cannot add or update a child row: a foreign key constraint fails ('u19_meso'.'_segmentation', CONSTRAINT '_segmentation_ibfk_1' FOREIGN KEY ('cross_chunks_reference_image') REFERENCES '~external_mesoimaging' ('hash'))` on insert with external blob . It looks like when ingesting into the table segmentation, the entry in the `~external_mesoimaging` not generated (the table is there, empty). 

Issue might be unspecific to external blob but rather to blob arguments into query.

### PR DESCRIPTION
**Pull request by guzman-raphael**
Fix #217

### CODE REVIEW

File: +dj/Relvar.m [hunk 1]
```diff
@@ -317,8 +317,8 @@ function insert(self, tuples, command)
                 valueStr = '';
                 for i = find(ix)
                     [v, placeholder] = makePlaceholder(i, tuple.(header.attributes(i).name));
-                    if ~isempty(v) && ( ...
-                            (~isnumeric(v) && ~islogical(v)) || (~isscalar(v) && ~isempty(v)))
+                    if header.attributes(i).isBlob || header.attributes(i).isString && ...
```
Comment (dimitri-yatsenko) [inline +dj/Relvar.m:320]: shouldn't this be
```matlab
if  (header.attributes(i).isBlob || header.attributes(i).isString) && ~isempty(v)
```
(missing parenthesis)

Comment (guzman-raphael) [reply +dj/Relvar.m:320]: @dimitri-yatsenko actually this is not the most updated one. Have a look in #220. That is the one that should be reviewed.
