### PR TITLE
Fix SQL argument growth condition

### LINKED ISSUE #217: External Blob: Insert fails due to `foreign key constraint` in `~external_%` table
Princeton reported an error that `Cannot add or update a child row: a foreign key constraint fails ('u19_meso'.'_segmentation', CONSTRAINT '_segmentation_ibfk_1' FOREIGN KEY ('cross_chunks_reference_image') REFERENCES '~external_mesoimaging' ('hash'))` on insert with external blob . It looks like when ingesting into the table segmentation, the entry in the `~external_mesoimaging` not generated (the table is there, empty). 

Issue might be unspecific to external blob but rather to blob arguments into query.

### PR DESCRIPTION
**Pull request by guzman-raphael**
Fix #217

### CODE REVIEW

File: +dj/Relvar.m [hunk 1]
```diff
@@ -215,35 +215,36 @@ function insert(self, tuples, command)
                 %   value:      <var> Processed, in-place value ready for insert.
                 %   placeholder:<string> Placeholder for argument substitution.
                 %   attr_idx:   <num> Attribute order index.
-                if header.attributes(attr_idx).isString
+                if isempty(value) || (header.attributes(attr_idx).isNumeric && isnan(value))
```
Comment (dimitri-yatsenko) [inline +dj/Relvar.m:218]: What about an empty string? I will review this more carefully later tonight. But keep in mind that empty strings are distinct from `null`.

Comment (guzman-raphael) [reply +dj/Relvar.m:218]: Good point, I will review/test it once more too. How are nulls expected to return from a fetch for the common datatypes?

Comment (guzman-raphael) [reply +dj/Relvar.m]: Addressed
