### PR TITLE
Modify update to allow nullable updates for strings/date

### LINKED ISSUE #211: update back to null does not work for date or datetime
matlab analog of: https://github.com/datajoint/datajoint-python/issues/664

### PR DESCRIPTION
**Pull request by guzman-raphael**
Fix #211 
also:
- Fixes bug with `createSchema` on MySQL8
- Updates unit tests to new structure
- Add doc on running unit tests locally

### CODE REVIEW

File: +dj/Relvar.m [hunk 1]
```diff
@@ -352,14 +352,25 @@ function update(self, attrname, value)
             
             switch true
                 case isNull
+                    assert(header.attributes(ix).isnullable, ...
+                            'attribute `%s` is not nullable.', attrname)
                     valueStr = 'NULL';
                     value = {};
                 case header.attributes(ix).isString
                     assert(dj.lib.isString(value), 'Value must be a string')
```
Comment (eywalker) [inline +dj/Relvar.m:360]: Actually I don't think this will allow for inserting `[]` as `isString([])` would be false.

[the remark this answers is not in the document]
Comment (guzman-raphael) [reply +dj/Relvar.m:362]: Addressed

Comment (guzman-raphael) [reply +dj/Relvar.m:362]: Addressed

File: +dj/Relvar.m [hunk 2]
```diff
@@ -343,40 +343,32 @@ function update(self, attrname, value)
...
                     value = {char(value)};
                 case header.attributes(ix).isBlob
-                    if isempty(value) && header.attributes(ix).isnullable
-                        valueStr = 'NULL';
-                        value = {};
-                    else
-                        valueStr = '"{M}"';
-                        value = {value};
-                    end
+                    valueStr = '"{M}"';
```
Comment (dimitri-yatsenko) [inline +dj/Relvar.m:366]: how is NULL handled here?

Comment (dimitri-yatsenko) [reply +dj/Relvar.m:366]: oh, I see, it's already handled together for all attribute types.

File: +dj/Relvar.m [hunk 3]
```diff
@@ -343,40 +343,32 @@ function update(self, attrname, value)
...
-            assert(count(self)==1, 'Update is only allowed on one tuple at a time')
-            isNull = nargin<3;
+            assert(count(self)==1, 'Update is only allowed on one tuple at a time');
             header = self.header;
             ix = find(strcmp(attrname,header.names));
-            assert(numel(ix)==1, 'invalid attribute name')
-            assert(~header.attributes(ix).iskey, 'cannot update a key value. Use insert(..,''REPLACE'') instead')
+            assert(numel(ix)==1, 'invalid attribute name');
+            assert(~header.attributes(ix).iskey, ...
+                'cannot update a key value. Use insert(..,''REPLACE'') instead');
```
Comment (eywalker) [inline +dj/Relvar.m:351]: beautifully handled
